services:
  postgres:
    image: postgres:15
    container_name: db_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: db_operaciones
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d db_operaciones"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ===== KEYCLOAK =====
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/db_operaciones
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
      - --http-port=8080
      - --hostname-strict=false
      - --import-realm          # ðŸ‘ˆ acÃ¡ le decimos que importe los realms del directorio /opt/keycloak/data/import
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import   # ðŸ‘ˆ montamos tu JSON dentro del contenedor
    depends_on:
      postgres:
        condition: service_healthy

  # ===== API GATEWAY =====
  api-gateway:
    container_name: api_gateway
    build:
      context: .
      dockerfile: ./gateway.dockerfile
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_started
      ms-operaciones:
        condition: service_started
      ms-transporte:
        condition: service_started
      ms-tarifa:
        condition: service_started
      ms-seguimiento:
        condition: service_started

  # ===== MICROSERVICIOS =====
  ms-operaciones:
    container_name: ms_operaciones
    build:
      context: .
      dockerfile: ./dockerfile
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/db_operaciones?currentSchema=operaciones
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SERVER_PORT: 8082
    depends_on:
      postgres:
        condition: service_healthy

  ms-transporte:
    container_name: ms_transporte
    build:
      context: .
      dockerfile: ./transporte.dockerfile
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/db_operaciones?currentSchema=transporte
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SERVER_PORT: 8083
      CLIENTS_TRACKING_URL: http://ms-seguimiento:8085
      CLIENTS_OPENCAGE_KEY: ""
    depends_on:
      postgres:
        condition: service_healthy

  ms-tarifa:
    container_name: ms_tarifa
    build:
      context: .
      dockerfile: ./tarifa.dockerfile
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/db_operaciones?currentSchema=tarifa
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SERVER_PORT: 8084
    depends_on:
      postgres:
        condition: service_healthy

  ms-seguimiento:
    container_name: ms_seguimiento
    build:
      context: .
      dockerfile: ./seguimiento.dockerfile
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/db_operaciones?currentSchema=seguimiento
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SERVER_PORT: 8085
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
